/*
    Utilities for getting/printing moves. Also see get_winning_moves.h

    "subgame_moves" and "sum_moves" variants return/print moves in the order
    they are generated by the underlying move_generator or
    sumgame_move_generator, without any deduplication/sorting.

    "winning_moves" variants are deduplicated and sorted according to
    sort_winning_moves() (from get_winning_moves.h)
*/
#pragma once

#include <memory>
#include <string>

#include "file_parser.h"
#include "sumgame.h"
#include "cgt_basics.h"

std::string sumgame_move_to_string(const sumgame& sum, const sumgame_move& sm,
                                   ebw player, bool with_subgame_idx);

////////////////////////////////////////////////// Get moves
std::vector<std::string> get_sum_moves(const sumgame& sum, bw player);
std::vector<std::string> get_subgame_moves(const game* g, bw player);

////////////////////////////////////////////////// Print moves
void print_winning_moves_for_player(std::ostream& os, sumgame& sum, ebw player);
void print_sum_moves_for_player(std::ostream& os, const sumgame& sum,
                                bw player);

void print_subgame_moves_for_player(std::ostream& os, const game* g, bw player);

////////////////////////////////////////////////// Print moves by input chunk
void print_winning_moves_by_chunk(std::ostream& os,
                                  std::shared_ptr<file_parser> parser);

void print_sum_moves_by_chunk(std::ostream& os,
                              std::shared_ptr<file_parser> parser);

void print_subgame_moves_by_chunk(std::ostream& os,
                                  std::shared_ptr<file_parser> parser);
