#pragma once

enum size_score_enum
{
    SIZE_SCORE_NONE = 0,
    SIZE_SCORE_BOARD_SIZE,
    SIZE_SCORE_NODE_COUNT,
    SIZE_SCORE_STONE_COUNT,
    SIZE_SCORE_TREE_HEIGHT,
    SIZE_SCORE_MAX_LOCAL_OPTIONS,
    SIZE_SCORE_PAIR,
};
